### ISSUE TITLE
Priority has no effect for registered components

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionutils#17]
https://github.com/nion-software/nionutils/blob/d05d6614f4885242652e9373a27779d1d8375f9d/nion/utils/Registry.py#L100

This should return ``sorted_components``, instead it returns ``components`` which makes priority have no effect.

**Comment by cmeyer** [comment]
Good catch. Fixed df29cca839bcd9ccd287e771197d3f92e890ebb2
